require('plugins_config.cmp')
--require('plugins_config.solarized')
require('plugins_config.telescope')
require('plugins_config.autopairs')
--require('plugins_config.lualine')
--require('plugins_config.treesitter')
--require('plugins_config.toggleterm')
require('plugins_config.mason_lsp')
